# Generated by Django 4.2 on 2023-06-07 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_amount', models.PositiveIntegerField(default=1000)),
                ('email_address', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RapidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50, unique=True)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_abandoned', models.PositiveIntegerField(default=0)),
                ('player_elo', models.PositiveIntegerField(default=1000)),
                ('raider_medals', models.PositiveIntegerField(default=0)),
                ('defender_medals', models.PositiveIntegerField(default=0)),
                ('attacker_medals', models.PositiveIntegerField(default=0)),
                ('population_medals', models.PositiveIntegerField(default=0)),
                ('total_population', models.PositiveIntegerField(default=0)),
                ('total_raid_points', models.PositiveIntegerField(default=0)),
                ('total_atk_points', models.PositiveIntegerField(default=0)),
                ('total_def_points', models.PositiveIntegerField(default=0)),
                ('player_type', models.CharField(max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ClassicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_abandoned', models.PositiveIntegerField(default=0)),
                ('player_elo', models.PositiveIntegerField(default=1000)),
                ('raider_medals', models.PositiveIntegerField(default=0)),
                ('defender_medals', models.PositiveIntegerField(default=0)),
                ('attacker_medals', models.PositiveIntegerField(default=0)),
                ('population_medals', models.PositiveIntegerField(default=0)),
                ('total_population', models.PositiveIntegerField(default=0)),
                ('total_raid_points', models.PositiveIntegerField(default=0)),
                ('total_atk_points', models.PositiveIntegerField(default=0)),
                ('total_def_points', models.PositiveIntegerField(default=0)),
                ('player_type', models.CharField(max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
